### ISSUE TITLE
Get survey, labels argument seems to be not working

### ISSUE THREAD

**Issue by vessisr** [ppssphysics/QualtricsInR#7]
useLabels in get_survey_responses() does not seem to be working. Still downloading labels.

QualtricsInR::get_survey_responses(surveys[ i,"id"], exportResponsesInProgress = FALSE, 
                                                  breakoutSets=FALSE, useLabels = FALSE)

**Comment by ppssphysics** [comment]
I just tested on my side and it works fine. As per the [documentation](https://api.qualtrics.com/api-reference/reference/responseImportsExports.json/paths/~1surveys~1%7BsurveyId%7D~1export-responses/post), the default is that labels are not used for answer choices. If you want the labels, you need to set useLabels to TRUE:

`QualtricsInR::get_survey_responses(surveys[ i,"id"], exportResponsesInProgress = FALSE,
breakoutSets=FALSE, useLabels = TRUE)`

I've added an example in the [documentation](https://qualtrics.psaouter.com/articles/survey-responses.html) to make it clearer. Hope this helps.
